import { type Item } from './db';

// Seeded items imported from MPPHSCL Live Rate Contracts (Date: 26/07/2026)
export const rateContractItems: Omit<Item, 'id'>[] = [
  {
    name: "Adult - Double Lumen Catheter Set(Size: 11.5 Fr-12 Fr, 13cm to 15cm (Curved))",
    category: "catheter",
    manufacturer: "Cardiomac India Private Limited",
    modelSize: "Size: 11.5 Fr-12 Fr, 13cm to 15cm (Curved",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 595,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Adult - Double Lumen Catheter Set(Size: 11.5 Fr-12 Fr, 13cm to 15cm (straight))",
    category: "catheter",
    manufacturer: "Cardiomac India Private Limited",
    modelSize: "Size: 11.5 Fr-12 Fr, 13cm to 15cm (straight",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 595,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Adult Femoral introducer sheath- 10-12 cm long()",
    category: "sheath",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507005",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 870,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Angiographic GuideWire(Amplatz Extra stiff guide wire)",
    category: "guidewire",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Amplatz Extra stiff guide wire",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 3750,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Angiographic GuideWire(Amplatz Super stiff guide wire)",
    category: "guidewire",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Amplatz Super stiff guide wire",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 3750,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Angiographic GuideWire-(J tip)",
    category: "guidewire",
    manufacturer: "Meditech Devices Private Limited",
    modelSize: "J tip",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 193,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Angiographic GuideWire(J tip, exchange length)",
    category: "guidewire",
    manufacturer: "Meditech Devices Private Limited",
    modelSize: "J tip, exchange length",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-08-03",
    unitCost: 289,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Angiographic Guidewire('J' tip, - Hydrophilic polymer coated)",
    category: "guidewire",
    manufacturer: "Meditech Devices Private Limited",
    modelSize: "'J' tip, - Hydrophilic polymer coated",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 786,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Angiographic Guidewire-  'J' tip, - Hydrophilic polymer coated Exchange length(250-260cm)( )",
    category: "guidewire",
    manufacturer: "Terumo India Private Limited",
    modelSize: "250-260cm",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 2000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Angiographic GuideWire(Straight tip)",
    category: "guidewire",
    manufacturer: "Meditech Devices Private Limited",
    modelSize: "Straight tip",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 189,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Angiographic Guidewire('Straight' tip, - Hydrophilic polymer coated Standard length (150-180cm))",
    category: "guidewire",
    manufacturer: "Meditech Devices Private Limited",
    modelSize: "'Straight' tip, - Hydrophilic polymer coated Standard length (150-180cm",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 890,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "aortic valvuloplasty balloon(catheters set)",
    category: "balloon",
    manufacturer: "Advanced Lifesciences Pvt Ltd",
    modelSize: "catheters set",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 47500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Balloon Aortic(valvuloplasty)",
    category: "balloon",
    manufacturer: "Advanced Lifesciences Pvt Ltd",
    modelSize: "valvuloplasty",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 47500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Balloon expandable stainless-steel peripheral stents(0.018 wire compatible)",
    category: "stent",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "0.018 wire compatible",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 25000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Balloon expandable stainless-steel peripheral stents(0.035 wire compatible)",
    category: "stent",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "0.035 wire compatible",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 25000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Cardiac Catheterization Catheters (Angled Pigtail catheter)()",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Angled Pigtail catheter",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-02-28",
    unitCost: 1000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Cardiac Catheterization Catheters(Marker Pigtail catheter)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Marker Pigtail catheter",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 1000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Cardiac Catheterization Catheters (Pigtail catheter for adult use)()",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Pigtail catheter for adult use",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-02-28",
    unitCost: 1000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Carotid Angiography catheters (Head Hunter)()",
    category: "catheter",
    manufacturer: "Terumo India Private Limited",
    modelSize: "Head Hunter",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 955,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Carotid Angiography catheters- (Simmons)()",
    category: "catheter",
    manufacturer: "Terumo India Private Limited",
    modelSize: "Simmons",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 955,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Carotid Angioplasty Sheath()",
    category: "sheath",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507016",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 12022,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Central Venous Catheter Kit(Single Lumen),Kit [700210]",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "Single Lumen",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 422,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Close Wound Drainage Device Under Negative Pressure(closed wound suction unit) Size 200 ml(catheter size 16, Each)",
    category: "catheter",
    manufacturer: "Sterimed Medical Devices Pvt Ltd",
    modelSize: "closed wound suction unit",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 91,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Close Wound Drainage Device Under Negative Pressure(closed wound suction unit) Size 200 ml(catheter size 18, Each)",
    category: "catheter",
    manufacturer: "Sterimed Medical Devices Pvt Ltd",
    modelSize: "closed wound suction unit",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 91,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Contrast Luerlock Syringe  (10 cc, with Luer Lock)()",
    category: "consumable",
    manufacturer: "Dr Surgical",
    modelSize: "10 cc, with Luer Lock",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-02-28",
    unitCost: 189,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Cutting Balloon(Catheter)",
    category: "balloon",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Catheter",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 40000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Disposable Suction Catheter(Size 12)",
    category: "catheter",
    manufacturer: "Devparv Surgico",
    modelSize: "Size 12",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 3,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Disposable Suction Catheter(Size 14)",
    category: "catheter",
    manufacturer: "Devparv Surgico",
    modelSize: "Size 14",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 3,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Double Lumen Polyurethane CVP Catheter 4 to 5 Fr(Length 8 to 13 cm,)",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "Length 8 to 13 cm,",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 466,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Drug Eluting coronary balloons(Paclitaxel)",
    category: "balloon",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Paclitaxel",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 35300,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Drug Eluting coronary balloons(Sirolimus)",
    category: "balloon",
    manufacturer: "Envision Scientific Private Limited",
    modelSize: "Sirolimus",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 35500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Everolimus stents(biostable polymer)",
    category: "stent",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "biostable polymer",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 22500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Feeding Tube (Catheter)(10 G, Each)",
    category: "catheter",
    manufacturer: "Biosurge Healthcare India Pvt Ltd",
    modelSize: "Catheter",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 2,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Catheters Double Lumen Kit Curved Double Lumen Catheter Set(12 F (Curved) Adult)",
    category: "catheter",
    manufacturer: "Cardiomac India Private Limited",
    modelSize: "12 F (Curved",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 669,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Catheters Single Lumen Set Adult(Size - 6F to 8F, length 13 cm to 15 cm, Each)",
    category: "catheter",
    manufacturer: "St Stone Medical Devices Private Limited",
    modelSize: "Size - 6F to 8F, length 13 cm to 15 cm, Each",
    batchLotNo: "RC-T-560",
    expiryDate: "2026-07-30",
    unitCost: 120,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Coronary Angiography diagnostic catheters(Greater than or equal to 100cm)",
    category: "catheter",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Greater than or equal to 100cm",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 599,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Coronary Angiography diagnostic catheters(Greater than or equal to 125cm)",
    category: "catheter",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Greater than or equal to 125cm",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 599,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters- 3D right guiding catheter,(6F/7F/8F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "6F/7F/8F",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters-Amplatz Left (Curves AL0.75, AL1, AL1.5, AL2, AL3),(5F/6F/7F/8F.)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Curves AL0.75, AL1, AL1.5, AL2, AL3",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters-Amplatz Right (Curves AR1,AR 1.2,AR2),(5F/6 F/7F/8F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Curves AR1,AR 1.2,AR2",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters- Extra back-up (EBU) left(5F/6F/7F/8F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "EBU",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters-Extra back-up (EBU) right,(5F/6F/7F/8F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "EBU",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters-Hockey Stick guiding catheter,(6F/7F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "6F/7F",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters- IMA guiding catheter,(Size 5F/6F/7F.)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Size 5F/6F/7F.",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters - Judkins left without side holes (Curves 3, 3.5, 4, 5 cm),(Size 5F/6F/7F/8F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Curves 3, 3.5, 4, 5 cm",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters- Judkins left with side holes (Curves 3, 3.5, 4, 5 cm),(Size 5F/6F/7F/8F.)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Curves 3, 3.5, 4, 5 cm",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters- Judkins right without side holes (Curves 3, 3.5, 4, 5 cm),(Size 5F/6F/7F/8F.)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Curves 3, 3.5, 4, 5 cm",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters-Judkins Right with side holes (Curves 3, 3.5, 4, 5 cm),(Size 5F/6F/7F/8F.)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Curves 3, 3.5, 4, 5 cm",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters- Left coronary bypass guide catheter( 6F/7F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "6F/7F",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters- Multipurpose (AI, AII),(Size 5F/6F/7F/8F.)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "AI, AII",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters-Right coronary bypass guide catheter(6F/7F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "6F/7F",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters-Short Amplatz Left (Curves 0.75, 1.0, 1.5, 2.0, 2.5, 3, 4);(5F/6F/7F/8F.)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Curves 0.75, 1.0, 1.5, 2.0, 2.5, 3, 4",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Femoral Guiding Catheters-Short Amplatz Right (Curves 1.0, 2.0);(5F/6F/7F/8F)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Curves 1.0, 2.0",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "FFR Catheter(Model- Comet II Pressure Guide wire)",
    category: "guidewire",
    manufacturer: "Arsh Traders",
    modelSize: "Model- Comet II Pressure Guide wire",
    batchLotNo: "RC-T-448",
    expiryDate: "2028-09-11",
    unitCost: 50000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Gadolinium Contrast(20 ml Vial)(Make Biophare India pharmaceticals pvt ltd Model Gadolinium Contrast(20 ml Vial))",
    category: "consumable",
    manufacturer: "Biophore India Pharmaceuticals Pvt Ltd",
    modelSize: "20 ml Vial",
    batchLotNo: "RC-T-737",
    expiryDate: "2027-09-03",
    unitCost: 635,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Guide Catheter Extension(Mother and child)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Mother and child",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-08-12",
    unitCost: 35000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Hickman Catheter single lumen(4.2 Fr As Per Attached Specification)",
    category: "catheter",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "4.2 Fr As Per Attached Specification",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 10000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Hickman Catheter single lumen(6.6 Fr As Per Attached Specification)",
    category: "catheter",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "6.6 Fr As Per Attached Specification",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 10000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Infant Feeding Tube (Catheter) Size: 3G(No.)",
    category: "catheter",
    manufacturer: "Biosurge Healthcare India Pvt Ltd",
    modelSize: "Catheter",
    batchLotNo: "RC-T-607",
    expiryDate: "2026-10-20",
    unitCost: 2,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Infant Feeding Tube (Catheter)(Size: 4G)",
    category: "catheter",
    manufacturer: "Biosurge Healthcare India Pvt Ltd",
    modelSize: "Catheter",
    batchLotNo: "RC-T-607",
    expiryDate: "2026-10-20",
    unitCost: 2,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Infant Feeding Tube((Catheter) Size: 5G)",
    category: "catheter",
    manufacturer: "Rudraksh Pharma And Surgico Pvt Ltd",
    modelSize: "(Catheter",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 2,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Infant Feeding Tube (Catheter) Size: 8G(Each)",
    category: "catheter",
    manufacturer: "Rudraksh Pharma And Surgico Pvt Ltd",
    modelSize: "Catheter",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 2,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Iopromide(Non Lonic Iodine Base Contrast Media 370mg 100ml)(Make bayer AG Model ultravist)",
    category: "consumable",
    manufacturer: "Bayer Pharmaceuticals Private Limited",
    modelSize: "Non Lonic Iodine Base Contrast Media 370mg 100ml",
    batchLotNo: "RC-T-737",
    expiryDate: "2027-09-03",
    unitCost: 1629,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "I.V Cannula for single use (Intravascular Catheters) BIS (Gauze 22,length 25) Consumable(Each)",
    category: "catheter",
    manufacturer: "Cardiomac India Private Limited",
    modelSize: "Intravascular Catheters",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 4,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "IVUS Catheter(Model- Opticross HD (60 MHZ))",
    category: "catheter",
    manufacturer: "Arsh Traders",
    modelSize: "Model- Opticross HD (60 MHZ",
    batchLotNo: "RC-T-448",
    expiryDate: "2028-09-11",
    unitCost: 65000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 14- 2 Way Each)",
    category: "balloon",
    manufacturer: "Devparv Surgico",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 13,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 14- 2 Way Each)",
    category: "balloon",
    manufacturer: "Life O Line Technologist",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 13,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 14- 2 Way Each)",
    category: "balloon",
    manufacturer: "Medevis Rubplast India Private Limited",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 13,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 16- 2 Way Each)",
    category: "balloon",
    manufacturer: "Life O Line Technologist",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 13,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 16- 2 Way Each)",
    category: "balloon",
    manufacturer: "Medevis Rubplast India Private Limited",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 13,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 16- 2 Way Each)",
    category: "balloon",
    manufacturer: "Devparv Surgico",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 13,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 18- 2 Way, Each)",
    category: "balloon",
    manufacturer: "Medevis Rubplast India Private Limited",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 14,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 18- 2 Way, Each)",
    category: "balloon",
    manufacturer: "Life O Line Technologist",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 14,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Latex Based Baloon capacity (30-50ml) Foleys Catheter(Size 18- 2 Way, Each)",
    category: "balloon",
    manufacturer: "Devparv Surgico",
    modelSize: "30-50ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 14,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "latex based baloon capacity (3 ml) Foleys Catheter(3 way, size - 12)",
    category: "balloon",
    manufacturer: "Syana India Associates",
    modelSize: "3 ml",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 32,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Long Line Silicon Catheter(G-24, Fr-2, L-30cm),Consumable [MIS76]",
    category: "catheter",
    manufacturer: "Vygon India Pvt Ltd",
    modelSize: "G-24, Fr-2, L-30cm",
    batchLotNo: "RC-T-560",
    expiryDate: "2026-07-30",
    unitCost: 3009,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Microcatheter for coil embolization()",
    category: "catheter",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507015",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 21504,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Microcatheters For antegrade technique()",
    category: "catheter",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507014",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 23500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Paediatric Epidural Set(19G Needle, Metal Stylet,22g Catheter,0.22Micron Epidural Catheter LOR Syringe)( )",
    category: "catheter",
    manufacturer: "St Stone Medical Devices Private Limited",
    modelSize: "19G Needle, Metal Stylet,22g Catheter,0.22Micron Epidural Catheter LOR Syringe",
    batchLotNo: "RC-T-560",
    expiryDate: "2026-07-30",
    unitCost: 350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral balloons(0.014 guide wire)",
    category: "balloon",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "0.014 guide wire",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 12075,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral balloons(0.018 guide wire)",
    category: "balloon",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "0.018 guide wire",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 12075,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral balloons(0.035 guide wire)",
    category: "balloon",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "0.035 guide wire",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 17865,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral Carotid stents self-expandable(Closed Cell)",
    category: "stent",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Closed Cell",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 36800,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral Carotid stents self(expandable)",
    category: "stent",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "expandable",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 33000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral Cutting balloons(-)",
    category: "balloon",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "-",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 50600,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral drug (Paclitaxel)(eluting balloon )",
    category: "balloon",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Paclitaxel",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 41800,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral drug((Sirolimus) eluting balloon )",
    category: "balloon",
    manufacturer: "Envision Scientific Private Limited",
    modelSize: "(Sirolimus",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 45000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral Guidewires(0.018 Guide wire)",
    category: "guidewire",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "0.018 Guide wire",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 5463,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral inserted central catheter(4 Fr)",
    category: "catheter",
    manufacturer: "Teleflex Medical Private Limited",
    modelSize: "4 Fr",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 8763,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral inserted central catheter(5 Fr (As per attached specification))",
    category: "catheter",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "5 Fr (As per attached specification",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 10036,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral Renal Balloon mounted stent(0.018 Guidewire)",
    category: "stent",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "0.018 Guidewire",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 25000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral stent graft(Balloon expandable)",
    category: "stent",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "Balloon expandable",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 93096,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral stent graft(Balloon expandable with PTFE)",
    category: "stent",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "Balloon expandable with PTFE",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 93096,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral stent graft(Covered stents)",
    category: "stent",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "Covered stents",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 86199,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Peripheral stent graft(Self-expandable)",
    category: "stent",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "Self-expandable",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 87152,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTCA Balloon catheter(Post-dilatation High pressure NC balloon (RBP 18-20 atm))",
    category: "balloon",
    manufacturer: "Sahajanand Medical Technologies Limited",
    modelSize: "Post-dilatation High pressure NC balloon (RBP 18-20 atm",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 3600,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTCA Balloon catheter(Post-dilatation High pressure NC balloon (RBP 20-22 atm))",
    category: "balloon",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "Post-dilatation High pressure NC balloon (RBP 20-22 atm",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 4499,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTCA Balloon catheter(Post-dilatation High pressure NC balloon (RBP Less than or equal to16 atm))",
    category: "balloon",
    manufacturer: "Sahajanand Medical Technologies Limited",
    modelSize: "Post-dilatation High pressure NC balloon (RBP Less than or equal to16 atm",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 3500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTCA Balloon Catheter(Predilataion SC balloon: Low entry profile)",
    category: "balloon",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Predilataion SC balloon: Low entry profile",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 4500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTCA Balloon Catheter(Predilataion Semi compliant balloon)",
    category: "balloon",
    manufacturer: "Innvolution Healthcare Pvt Ltd",
    modelSize: "Predilataion Semi compliant balloon",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 5500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTCA Balloon Catheter(Predilataion semi compliant balloon: Ultralow entry profile)",
    category: "balloon",
    manufacturer: "Innvolution Healthcare Pvt Ltd",
    modelSize: "Predilataion semi compliant balloon: Ultralow entry profile",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 5500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTCA insertion needle accepting(0.014 guide wires)",
    category: "guidewire",
    manufacturer: "Invent Bio-Med Private Limited",
    modelSize: "0.014 guide wires",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 44,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTCA insertion needle accepting(0.035 guide wires)",
    category: "guidewire",
    manufacturer: "Invent Bio-Med Private Limited",
    modelSize: "0.035 guide wires",
    batchLotNo: "RC-T-567",
    expiryDate: "2026-09-25",
    unitCost: 44,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "PTMC Balloon with accessories(without vent tube)",
    category: "balloon",
    manufacturer: "Translumina Therapeutics Pvt Ltd",
    modelSize: "without vent tube",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 58000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Pulmonary valvuloplasty balloon(catheters set)",
    category: "balloon",
    manufacturer: "Advanced Lifesciences Pvt Ltd",
    modelSize: "catheters set",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 47500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radial/Brachial introducer sheath()",
    category: "sheath",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507008",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 1100,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radial coronary angioplasty(guiding catheters)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "guiding catheters",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-09-25",
    unitCost: 3350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radial coronary angioplasty guiding catheters-  Ikari left curve()",
    category: "catheter",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507011",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 4800,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radial coronary angioplasty guiding catheters Ikari right curve()",
    category: "catheter",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507012",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 4800,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radial coronary angioplasty guiding catheters(tiger type curve)",
    category: "catheter",
    manufacturer: "Terumo India Private Limited",
    modelSize: "tiger type curve",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 4800,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radial diagnostic angiography catheter-(Multipurpose A like Curve)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Multipurpose A like Curve",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-08-12",
    unitCost: 1200,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radial diagnostic angiography catheter-(Tiger curve 4.0/ 4.5)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "Tiger curve 4.0/ 4.5",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-08-12",
    unitCost: 1200,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radio Opague Catheter With PTFE/Polyurethine/FEP/VOLEX Material(IV Safety Cannula With Luer Lock (G-22))",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "IV Safety Cannula With Luer Lock (G-22",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 12,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radio Opaque Catheter With PTFE/Polyurethine/FEP/VOLEX Material(IV Safety Cannula With Luer Lock (G-18))",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "IV Safety Cannula With Luer Lock (G-18",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 12,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Radio Opaque Catheter With PTFE/Polyurethine/FEP/VOLEX Material(IV Safety Cannula With Luer Lock (G-20))",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "IV Safety Cannula With Luer Lock (G-20",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 12,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Scoring  balloon(Catheter)",
    category: "balloon",
    manufacturer: "Innvolution Healthcare Pvt Ltd",
    modelSize: "Catheter",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 15000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Self-expanding peripheral stents(0.018 guidewire compatible)",
    category: "stent",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "0.018 guidewire compatible",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 27940,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Self-expanding peripheral stents(0.035  guidewire)",
    category: "stent",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "0.035  guidewire",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 25160,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Self-expanding peripheral stents(15-24 mm)",
    category: "stent",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "15-24 mm",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 39100,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Self-expanding peripheral stents(-)",
    category: "stent",
    manufacturer: "Boston Scientific India Pvt Ltd",
    modelSize: "-",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 39100,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Self-expanding peripheral stents(Vascular mimetic stents)",
    category: "stent",
    manufacturer: "Bard India Healthcare Pvt Ltd",
    modelSize: "Vascular mimetic stents",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-07-26",
    unitCost: 53972,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Short IV Catheter With Straight/J tip Guidewire(L-20, Fr-2, G-22),Consumable [MIS108]",
    category: "guidewire",
    manufacturer: "St Stone Medical Devices Private Limited",
    modelSize: "L-20, Fr-2, G-22",
    batchLotNo: "RC-T-702",
    expiryDate: "2027-07-29",
    unitCost: 699,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Short IV Catheter With Straight/J tip Guidewire(L-4, Fr-2, G-22),Consumable [MIS109]",
    category: "guidewire",
    manufacturer: "Vygon India Pvt Ltd",
    modelSize: "L-4, Fr-2, G-22",
    batchLotNo: "RC-T-560",
    expiryDate: "2026-07-30",
    unitCost: 2205,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Single Umbilical Catheter With Leur Lock(Fr-2 to Fr 2.5, L-40 cm),Consumable [MIS111]",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "Fr-2 to Fr 2.5, L-40 cm",
    batchLotNo: "RC-T-702",
    expiryDate: "2027-07-29",
    unitCost: 910,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Single Umbilical Catheter With Leur Lock(Fr-3 to Fr 3.5 , L-40 cm),Consumable [MIS112]",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "Fr-3 to Fr 3.5 , L-40 cm",
    batchLotNo: "RC-T-702",
    expiryDate: "2027-07-29",
    unitCost: 595,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Single Umbilical Catheter With Luer Lock Stopcock(Fr-4, L-40 cm),Consumable [MIS113]",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "Fr-4, L-40 cm",
    batchLotNo: "RC-T-702",
    expiryDate: "2027-07-29",
    unitCost: 595,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Single Umbilical Catheter With Luer Lock Stopcock(Fr-5, L-40 cm),Consumable [MIS114]",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "Fr-5, L-40 cm",
    batchLotNo: "RC-T-702",
    expiryDate: "2027-07-29",
    unitCost: 595,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "SIROLIMUS ELUTING CORONARY STENT(biodegradable polymer with abluminal coating)",
    category: "stent",
    manufacturer: "Translumina Therapeutics Pvt Ltd",
    modelSize: "biodegradable polymer with abluminal coating",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 22500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "SIROLIMUS ELUTING CORONARY STENT(open cell design with ultra thin stent thickness)",
    category: "stent",
    manufacturer: "Sahajanand Medical Technologies Limited",
    modelSize: "open cell design with ultra thin stent thickness",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 18000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "SIROLIMUS ELUTING CORONARY STENT(Polymer free)",
    category: "stent",
    manufacturer: "Translumina Therapeutics Pvt Ltd",
    modelSize: "Polymer free",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 38267,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "SIROLIMUS ELUTING CORONARY STENT(stainless steel)",
    category: "stent",
    manufacturer: "Translumina Therapeutics Pvt Ltd",
    modelSize: "stainless steel",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 29500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "SIROLIMUS ELUTING CORONARY STENT(Ultra thin Strut thickness)",
    category: "stent",
    manufacturer: "Sahajanand Medical Technologies Limited",
    modelSize: "Ultra thin Strut thickness",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 38265,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Sizing balloon for ASD(Circular shape)",
    category: "balloon",
    manufacturer: "Vascular Concepts Limited",
    modelSize: "Circular shape",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 21116,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Steerable PTCA guide wires, 0.014, 180 -190 cm long, straight tip, duo core design for kink resistance with distal tip spring coil along with distal hydrophilic and silicon coating and PTFE coating of rest of the wire length with tip load  of 0.6 gm()",
    category: "guidewire",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507002",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 4800,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Steerable PTCA guide wires, 0.014, 180 -190 cm long, straight tip, duo core design for kink resistance with distal tip spring coil along with distal hydrophilic and silicon coating and PTFE coating of rest of the wire length with tip load  of 1 gm()",
    category: "guidewire",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507003",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 4800,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Steerable PTCA guide wires, 0.014, 180 -190 cm long, straight tip,  with distal tip spring coil along with distal hydrophilic and silicon coating and PTFE coating of rest of the wire length with tip load  of  0.5 gm to 3.6 gm()",
    category: "guidewire",
    manufacturer: "Terumo India Private Limited",
    modelSize: "202507004",
    batchLotNo: "RC-T-637",
    expiryDate: "2027-03-04",
    unitCost: 4800,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Stents for Coarctation of Aorta(Covered)",
    category: "stent",
    manufacturer: "Advanced Lifesciences Pvt Ltd",
    modelSize: "Covered",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 220000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Suction Catheter Assorted(10 no/each)",
    category: "catheter",
    manufacturer: "Biosurge Healthcare India Pvt Ltd",
    modelSize: "10 no/each",
    batchLotNo: "RC-T-607",
    expiryDate: "2026-10-20",
    unitCost: 3,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Suction Catheter, Sterile(Size Fg 20 (Disposable, Sterile each))",
    category: "catheter",
    manufacturer: "Biosurge Healthcare India Pvt Ltd",
    modelSize: "Size Fg 20 (Disposable, Sterile each",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 3,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Suction Catheter, Sterile(Size Fg 22 (Disposable, Sterile each))",
    category: "catheter",
    manufacturer: "Biosurge Healthcare India Pvt Ltd",
    modelSize: "Size Fg 22 (Disposable, Sterile each",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 3,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Suction Catheter, Sterile(Size Fg 6 (Disposable, Sterile each))",
    category: "catheter",
    manufacturer: "Biosurge Healthcare India Pvt Ltd",
    modelSize: "Size Fg 6 (Disposable, Sterile each",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 2,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Thrombosuction catheters(kink resistance)",
    category: "catheter",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "kink resistance",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-08-12",
    unitCost: 22000,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Titanium chemo Port with Silicon catheter (8 fr) Length -60cm-80cm, guide wire, peel-away desilet, Hubsite needle(22 G * 20 -25.4mm)",
    category: "closure device",
    manufacturer: "Vygon India Pvt Ltd",
    modelSize: "8 fr",
    batchLotNo: "RC-T-560",
    expiryDate: "2026-07-30",
    unitCost: 10989,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Titanium chemo Port with Silicon catheter (9.6 fr) Length -60cm-80cm, guide wire, peel-away desilet, Hubsite needle(22 G * 20 -25.4mm)",
    category: "closure device",
    manufacturer: "Vygon India Pvt Ltd",
    modelSize: "9.6 fr",
    batchLotNo: "RC-T-607",
    expiryDate: "2026-10-20",
    unitCost: 11868,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Triple Lumen Jugular Catheter Kit,(Size 12F, 16+/- 1cm, Kit)",
    category: "catheter",
    manufacturer: "Cardiomac India Private Limited",
    modelSize: "Size 12F, 16+/- 1cm, Kit",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 745,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Triple Lumen Polyurethane CVP Catheter 7 to 7.5Fr(G-14-16x18x18, Length 16-20 cm, Each)",
    category: "catheter",
    manufacturer: "Poly Medicure Ltd.",
    modelSize: "G-14-16x18x18, Length 16-20 cm, Each",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 422,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Triple Lumen Polyurethane CVP Catheter 7 to 7.5Fr(G-14-16x18x18, Length 16-20 cm, Each)",
    category: "catheter",
    manufacturer: "Cardiomac India Private Limited",
    modelSize: "G-14-16x18x18, Length 16-20 cm, Each",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-07-19",
    unitCost: 422,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Triple Lumen Polyurethane CVP Catheter 7 to 7.5 Fr(G-14-16x18x18x18, Length 15-16cm, Each)",
    category: "catheter",
    manufacturer: "Cardiomac India Private Limited",
    modelSize: "G-14-16x18x18x18, Length 15-16cm, Each",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 425,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Valvuloplasty(balloon)",
    category: "balloon",
    manufacturer: "Advanced Lifesciences Pvt Ltd",
    modelSize: "balloon",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 47500,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Wound Suction catheter(NO 18)",
    category: "catheter",
    manufacturer: "Life O Line Technologist",
    modelSize: "NO 18",
    batchLotNo: "RC-T-658",
    expiryDate: "2027-06-21",
    unitCost: 95,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Y-Connector Hemostatic valve(Type- push and release)",
    category: "consumable",
    manufacturer: "St Stone Medical Devices Private Limited",
    modelSize: "Type- push and release",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-08-08",
    unitCost: 350,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Y-Connector Hemostatic valve(Type- Rotatory mechanism)",
    category: "consumable",
    manufacturer: "St Stone Medical Devices Private Limited",
    modelSize: "Type- Rotatory mechanism",
    batchLotNo: "RC-T-569",
    expiryDate: "2026-08-08",
    unitCost: 300,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
  {
    name: "Zotarolimus(stents)",
    category: "stent",
    manufacturer: "India Medtronic Pvt Ltd",
    modelSize: "stents",
    batchLotNo: "RC-T-568",
    expiryDate: "2026-09-25",
    unitCost: 30095,
    currentQuantity: 0,
    reorderLevel: 5,
    storageLocation: "Cath Lab Store"
  },
];
